2018-01-04 23:16:30,671 [salt.utils.parsers                                   ][WARNING ][112] Minion received a SIGTERM. Exiting.
2018-01-05 15:42:05,696 [salt.utils.verify][WARNING ][4953] Insecure logging configuration detected! Sensitive data may be logged.
2018-01-05 15:43:21,376 [salt.utils.parsers][WARNING ][4953] Minion received a SIGINT. Exiting.
2018-01-05 16:20:30,987 [salt.utils.parsers][WARNING ][1785] Minion received a SIGTERM. Exiting.
2018-01-05 16:31:42,567 [salt.utils.parsers][WARNING ][9178] Minion received a SIGTERM. Exiting.
2018-01-05 16:32:57,177 [salt.utils.parsers][WARNING ][14776] Minion received a SIGTERM. Exiting.
2018-01-05 17:27:47,619 [salt.template    ][ERROR   ][30434] Template was specified incorrectly: False
2018-01-05 17:29:01,066 [salt.utils.verify][WARNING ][30861] Insecure logging configuration detected! Sensitive data may be logged.
2018-01-05 17:33:47,582 [salt.utils.verify][WARNING ][32018] Insecure logging configuration detected! Sensitive data may be logged.
2018-01-05 17:34:09,882 [salt.utils.verify][WARNING ][492] Insecure logging configuration detected! Sensitive data may be logged.
2018-01-05 17:37:32,444 [salt.utils.parsers][WARNING ][28184] Minion received a SIGTERM. Exiting.
2018-01-05 17:37:49,400 [salt.utils.verify][WARNING ][1691] Insecure logging configuration detected! Sensitive data may be logged.
2018-01-05 17:39:28,635 [salt.utils.verify][WARNING ][2146] Insecure logging configuration detected! Sensitive data may be logged.
2018-01-05 17:39:46,383 [salt.log.setup   ][ERROR   ][3045] An un-handled exception was caught by salt's global exception handler:
SaltRenderError: Unable to render top file. No targets found.
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 391, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 1619, in show_top
    top_ = st_.get_top()
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3109, in get_top
    return self.merge_tops(tops)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2895, in merge_tops
    return merge_func(tops)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2917, in _merge_tops_merge
    raise SaltRenderError('Unable to render top file. No targets found.')
SaltRenderError: Unable to render top file. No targets found.
2018-01-05 17:42:49,131 [salt.log.setup   ][ERROR   ][3796] An un-handled exception was caught by salt's global exception handler:
SaltRenderError: Unable to render top file. No targets found.
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 391, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 1619, in show_top
    top_ = st_.get_top()
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3109, in get_top
    return self.merge_tops(tops)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2895, in merge_tops
    return merge_func(tops)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2917, in _merge_tops_merge
    raise SaltRenderError('Unable to render top file. No targets found.')
SaltRenderError: Unable to render top file. No targets found.
2018-01-05 17:43:28,071 [salt.utils.verify][WARNING ][4006] Insecure logging configuration detected! Sensitive data may be logged.
2018-01-05 17:43:28,457 [salt.log.setup   ][ERROR   ][4006] An un-handled exception was caught by salt's global exception handler:
SaltRenderError: Unable to render top file. No targets found.
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 391, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 1619, in show_top
    top_ = st_.get_top()
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3109, in get_top
    return self.merge_tops(tops)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2895, in merge_tops
    return merge_func(tops)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2917, in _merge_tops_merge
    raise SaltRenderError('Unable to render top file. No targets found.')
SaltRenderError: Unable to render top file. No targets found.
2018-01-05 17:51:39,985 [salt.utils.verify][WARNING ][6356] Insecure logging configuration detected! Sensitive data may be logged.
2018-01-05 17:51:40,357 [salt.log.setup   ][ERROR   ][6356] An un-handled exception was caught by salt's global exception handler:
SaltRenderError: Unable to render top file. No targets found.
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 391, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 1619, in show_top
    top_ = st_.get_top()
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3109, in get_top
    return self.merge_tops(tops)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2895, in merge_tops
    return merge_func(tops)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2917, in _merge_tops_merge
    raise SaltRenderError('Unable to render top file. No targets found.')
SaltRenderError: Unable to render top file. No targets found.
2018-01-05 17:56:53,585 [salt.state       ][ERROR   ][8642] The named service salt-api is not available
2018-01-05 17:56:53,621 [salt.loaded.int.module.cmdmod][ERROR   ][8642] Command '['systemd-run', '--scope', 'systemctl', 'stop', 'salt-api.service']' failed with return code: 5
2018-01-05 17:56:53,621 [salt.loaded.int.module.cmdmod][ERROR   ][8642] stderr: Running scope as unit run-r709b37e4dc174f1dabbab4219c5647d2.scope.
Failed to stop salt-api.service: Unit salt-api.service not loaded.
2018-01-05 17:56:53,621 [salt.loaded.int.module.cmdmod][ERROR   ][8642] retcode: 5
2018-01-05 17:56:53,636 [salt.loaded.int.module.cmdmod][ERROR   ][8642] Command '['systemd-run', '--scope', 'systemctl', 'start', 'salt-api.service']' failed with return code: 5
2018-01-05 17:56:53,637 [salt.loaded.int.module.cmdmod][ERROR   ][8642] stderr: Running scope as unit run-rbc717363581d448a843ddda659d9de3e.scope.
Failed to start salt-api.service: Unit salt-api.service not found.
2018-01-05 17:56:53,637 [salt.loaded.int.module.cmdmod][ERROR   ][8642] retcode: 5
2018-01-05 17:56:53,638 [salt.state       ][ERROR   ][8642] Running scope as unit run-rbc717363581d448a843ddda659d9de3e.scope.
Failed to start salt-api.service: Unit salt-api.service not found.
2018-01-05 17:57:02,212 [salt.state       ][ERROR   ][8642] The named service salt-api is not available
2018-01-05 18:01:39,770 [salt.template    ][ERROR   ][11995] Template was specified incorrectly: False
2018-01-05 18:19:49,657 [salt.utils.verify][WARNING ][18198] Insecure logging configuration detected! Sensitive data may be logged.
